STANDARDS = [
    {"id": "machinery-risk", "framework": "EU Machinery Regulation", "reference": "2023/1230", "topic": "Risk assessment and risk reduction", "status": "DRAFT_MAPPING", "application_date": "2027-01-20", "metrics": ["frechet", "mean_drift", "workspace_violation_rate"], "source": "https://single-market-economy.ec.europa.eu/sectors/mechanical-engineering/machinery_en", "reviewed_on": "2026-10-01", "gap": "Product applicability, residual risks and assessor acceptance require independent review."},
    {"id": "machinery-controls", "framework": "EU Machinery Regulation", "reference": "2023/1230", "topic": "Safety-related control behavior", "status": "DRAFT_MAPPING", "application_date": "2027-01-20", "metrics": ["action_sensitivity", "max_speed", "max_jerk"], "source": "https://eur-lex.europa.eu/eli/reg/2023/1230/oj", "reviewed_on": "2026-10-01", "gap": "Exact legal clause and conformity route need legal review; software telemetry is not certified safety control."},
    {"id": "iso-industrial", "framework": "ISO 10218", "reference": "10218-1:2025 / 10218-2:2025", "topic": "Industrial robot and application safety", "status": "PUBLISHED_SCOPE_REVIEW", "application_date": None, "metrics": ["workspace_violation_rate", "contact_violation_rate"], "source": "https://www.iso.org/committee/5915511/x/catalogue/", "reviewed_on": "2026-10-01", "gap": "Use licensed standard text and a qualified safety assessor. Test coverage does not imply conformity."},
    {"id": "iso-stability", "framework": "ISO/CD 25785-1", "reference": "Committee Draft, stage 30.60", "topic": "Dynamically stable industrial mobile robots", "status": "UNDER_DEVELOPMENT", "application_date": None, "metrics": [], "source": "https://www.iso.org/committee/5915511/x/catalogue/", "reviewed_on": "2026-10-01", "gap": "No published final requirements or stability proof. Track draft evolution; do not claim certification."},
    {"id": "ai-data", "framework": "EU AI Act", "reference": "2024/1689", "topic": "Data governance and technical records", "status": "LEGAL_REVIEW_REQUIRED", "application_date": None, "metrics": ["synthetic_fraction", "diversity_loss"], "source": "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai", "reviewed_on": "2026-10-01", "gap": "Classification, amended implementation dates and sector-specific requirements need legal review."},
    {"id": "ai-oversight", "framework": "EU AI Act", "reference": "2024/1689", "topic": "Human oversight, robustness and monitoring", "status": "DRAFT_MAPPING", "application_date": None, "metrics": ["unsupported_perception_rate", "ensemble_spread", "distribution_shift"], "source": "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai", "reviewed_on": "2026-10-01", "gap": "Review workflow and diagnostic evidence support, but do not satisfy, all obligations."},
]

EMBODIMENTS = [
    {"id": "franka-panda", "name": "Franka Panda", "family": "manipulator", "degrees_of_freedom": 7, "coordinate_frame": "task", "units": "m", "dimension": 3, "hardware_validated": False, "description": "Reference task-space contract. Demonstration traces, not a connected arm."},
    {"id": "ur5e", "name": "UR5e", "family": "manipulator", "degrees_of_freedom": 6, "coordinate_frame": "task", "units": "m", "dimension": 3, "hardware_validated": False, "description": "Registered comparison contract. Synthetic geometric transfer, not robot validation."},
    {"id": "g1-task-space", "name": "G1 task-space", "family": "humanoid", "degrees_of_freedom": 29, "coordinate_frame": "task", "units": "m", "dimension": 3, "hardware_validated": False, "description": "Illustrative humanoid end-effector contract. No balance, fall, or locomotion validation."},
]